/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as QrRouteImport } from './routes/qr'
import { Route as MeRouteImport } from './routes/me'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as KIdRouteImport } from './routes/k.$id'
import { Route as AuthenticatedComposeRouteImport } from './routes/_authenticated/compose'
import { Route as ApiPublicRateKavithaiRouteImport } from './routes/api/public/rate-kavithai'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const KIdRoute = KIdRouteImport.update({
  id: '/k/$id',
  path: '/k/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComposeRoute = AuthenticatedComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRateKavithaiRoute = ApiPublicRateKavithaiRouteImport.update({
  id: '/api/public/rate-kavithai',
  path: '/api/public/rate-kavithai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/qr': typeof QrRoute
  '/search': typeof SearchRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/k/$id': typeof KIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/rate-kavithai': typeof ApiPublicRateKavithaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/qr': typeof QrRoute
  '/search': typeof SearchRoute
  '/compose': typeof AuthenticatedComposeRoute
  '/k/$id': typeof KIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/rate-kavithai': typeof ApiPublicRateKavithaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/qr': typeof QrRoute
  '/search': typeof SearchRoute
  '/_authenticated/compose': typeof AuthenticatedComposeRoute
  '/k/$id': typeof KIdRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/rate-kavithai': typeof ApiPublicRateKavithaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/me'
    | '/qr'
    | '/search'
    | '/compose'
    | '/k/$id'
    | '/u/$username'
    | '/api/public/rate-kavithai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/me'
    | '/qr'
    | '/search'
    | '/compose'
    | '/k/$id'
    | '/u/$username'
    | '/api/public/rate-kavithai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/me'
    | '/qr'
    | '/search'
    | '/_authenticated/compose'
    | '/k/$id'
    | '/u/$username'
    | '/api/public/rate-kavithai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MeRoute: typeof MeRoute
  QrRoute: typeof QrRoute
  SearchRoute: typeof SearchRoute
  KIdRoute: typeof KIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicRateKavithaiRoute: typeof ApiPublicRateKavithaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k/$id': {
      id: '/k/$id'
      path: '/k/$id'
      fullPath: '/k/$id'
      preLoaderRoute: typeof KIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compose': {
      id: '/_authenticated/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AuthenticatedComposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/rate-kavithai': {
      id: '/api/public/rate-kavithai'
      path: '/api/public/rate-kavithai'
      fullPath: '/api/public/rate-kavithai'
      preLoaderRoute: typeof ApiPublicRateKavithaiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComposeRoute: typeof AuthenticatedComposeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComposeRoute: AuthenticatedComposeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MeRoute: MeRoute,
  QrRoute: QrRoute,
  SearchRoute: SearchRoute,
  KIdRoute: KIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicRateKavithaiRoute: ApiPublicRateKavithaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
